networks:
  wg-network:
    ipam:
      config:
        - subnet: 172.19.0.0/16
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      wg-network:
        ipv4_address: 172.19.0.2
    ports:
      - "9091:9091/tcp"
      - "7878:7878"
      - "6767:6767"
      - "8989:8989"
      - "9117:9117"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    restart: always
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    network_mode: "service:wireguard"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./radarr/config:/config
      - ./radarr/data:/data
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./bazarr/config:/config
      - ./bazarr/data:/data
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/data:/data
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
